apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: connect-ecc
spec:
  entrypoint: ssh-instance
  volumes:
  - name: ssh-secret
    secret:
      secretName: ssh-key-secret
      defaultMode: 256
      items: 
        - key: my-keypair
          path: my-keypair
          mode: 256
  templates:
    - name: ssh-instance
      script: 
        image: docker.io/nightmar39/git-yq
        command: [bin/sh]
        source: |
          ls -la /secret/ssh
          ssh -o StrictHostKeyChecking=no -i "/secret/ssh/my-keypair" ec2-user@ec2-18-116-100-193.us-east-2.compute.amazonaws.com 'ansible-playbook helloWorld.yml'
        volumeMounts:
        - name: ssh-secret
          mountPath: "/secret/ssh"