apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: connect-ecc
spec:
  entrypoint: ssh-instance
  volumes:
  - name: ssh-secret
    secret:
      secretName: ssh-key-secret
      defaultMode: 0400
  templates:
    - name: ssh-instance
      script: 
        image: docker.io/nightmar39/git-yq
        command: [bin/sh]
        source: |
          ls -la /secret/ssh
          chmod 600 /secret/ssh/my-keypair
          ssh -i "/secret/ssh/my-keypair" ec2-user@ec2-18-116-100-193.us-east-2.compute.amazonaws.com 'df -H'
        volumeMounts:
        - name: ssh-secret
          mountPath: "/secret/ssh"
          readOnly: true