apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wf-print-loop
spec:
  entrypoint: step-loops
  arguments: 
    parameters: 
      - name: counter
        value: 0 
  templates:
  - name: step-loops
    steps: 
      - - name: printN
          template: task-template 
          arguments: 
              parameters : [{ name: counter, value: "{{item}}" }]
          withItems: [ 1, 2, 3, 4, 5, 6, 7 ,8, 9, 10 ]

  - name: task-template
    inputs:
      parameters: 
        - name: counter
    script:
      image: python:3.8-slim
      command: [python]
      source: |
        print("{{inputs.parameters.counter}}")